### ISSUE TITLE
Where are the files for the "layout-grids-code-along" exercise?

### ISSUE THREAD

**Issue by CodeByLine** [learn-co-students/layouts-grids-code-along-v-000#147]
Shouldn't there be a file to be forked? Or am I confused? Please explain.

**Comment by ga-be** [comment]
Probably too late for @CodeByLine, but if anyone else has the same question:

You'll be editing the `exceptional-realty-bootstrapped` project files you downloaded/modified in the [Bootstrap Code-Along](https://learn.co/lessons/bootstrap-codealong) lab. You can use the non-Bootstrapped `index.html` and `style.css` files from the project files for the [Adding Responsive Features Code-Along](https://learn.co/lessons/adding-responsive-features) to copypaste the same content as the video's narrator.

To the Learn.co curriculum team: it _is_ a bit confusing when the `learn open` command for this lab forks and clones a completely empty project file while the video (without any further clarification) expects us to continue working on the project files from the Bootstrap Code-Along.

**Comment by CodeByLine** [comment]
I have moved past that unit, but I am sure others will appreciate it. Thank you!

**Comment by alexcrisan** [comment]
This lesson should clarify how to move to files from the two other project folders into this project folder. I have moved the files manually with terminal and by just copy/pasting in Finder, but now when I try to push those changes, I get errors. This has been happening with a lot of projects. There seems to be some issue with pushing files that were copied manually. It doesn't work. I have to delete the entire project and fork it again... smh.

**Comment by gj** [comment]
>This lesson should clarify how to move to files from the two other project folders into this project folder. I have moved the files manually with terminal and by just copy/pasting in Finder, but now when I try to push those changes, I get errors. This has been happening with a lot of projects. There seems to be some issue with pushing files that were copied manually. It doesn't work. I have to delete the entire project and fork it again... smh.

@alexcrisan — are you using the IDE or a local development environment?

**Comment by alexcrisan** [comment]
IDE

**Comment by alexcrisan** [comment]
For some reason, when I tried to copy the folders using Learn IDE, it was telling me the directory does not exist. Same exact thing with Terminal worked..

**Comment by gj** [comment]
Were you using [the IDE's `Import File` function](https://learn.co/help-center#how-can-i-upload-files-to-my-repo-using-the-ide)?

I don't believe it supports uploading folders — only single files — so It makes uploading an entire repo to the IDE very tedious. You could try a couple other things:
* initialize the external directory containing all of the files you wish to import as a Git repository, sync it to GitHub, then `git clone` it into your IDE
* Use a minimal local environment to code along with this particular lesson. It's just HTML/CSS, so you don't really need anything more than a terminal, text editor, and Chrome.

**Comment by alexcrisan** [comment]
No, but that is the only way I could get things to work in a previous project. Through import. On this one, I did it by using commands like cp -rf images/ ~/directory, and then some things I had to go into the directory on my computer and copy them manually with the mouse and keyboard commands Cmd + C/V. Everything in the current directory looks exactly how it should, but it seems the Learn IDE is not recognizing this directory anymore because none of the git commands work anymore. This appears to be tied to the fact that I copied the files over manually, not through Learn's import function. Yes, it would be very tedious to copy all the files over through Import, one by one. 

I spend more time troubleshooting Learn than I do coding lol! I should get a discount on tuition lol.

**Comment by CodeByLine** [comment]
Strongly suggest you switch to Terminal. One of the fellow students urged me to switch fr IDE to Terminal and everything is MUCH easier after the switch. It took me a while to figure out how to ditch IDE and still pass tests. This is the trick: Add this line in the gemfile: `gem 'learn-co' ` and you can type `learn` and `learn submit` straight from the Terminal. Obviously you first need to fork and `git clone` onto your local computer. Add the `gem 'learn-co'` line. Type `rspec` (or `learn`) for tests. Then it's up to you if you want to get fancy with GitHub commands :-) Cut out the middleman & save a ton of hassle.

**Comment by gj** [comment]
The IDE is fine; it's just a matter of understanding its limitations.

>Strongly suggest you switch to Terminal. One of the fellow students urged me to switch fr IDE to Terminal and everything is MUCH easier after the switch. It took me a while to figure out how to ditch IDE and still pass tests. This is the trick: Add this line in the gemfile: gem 'learn-co' and you can type learn and learn submit straight from the Terminal. Obviously you first need to fork and git clone onto your local computer. Add the gem 'learn-co' line. Type rspec (or learn) for tests. Then it's up to you if you want to get fancy with GitHub commands :-) Cut out the middleman & save a ton of hassle.

@CodeByLine: you are manually installing the `learn-co` gem in every repository. If you add it to your default RubyGems environment, that step will be quite unnecessary. From any Terminal window, simply type `gem install learn-co`. I highly recommend that you take another look at the instructions [here](https://learn.co/manual_setup) for properly setting up your local development environment. You might be able to save time/effort elsewhere as well!

Also, to clarify: the choice isn't between the IDE and Terminal. It's between the IDE and an entire local development environment. Keeping that in mind makes it easier to appreciate how cool the IDE is. :smile:

**Comment by CodeByLine** [comment]
:-) Cool! I'll install the gem globally. Thanks! 

I tried the local dev environment setup several times, got stuck somewhere, prob on step 4.

IDE may have its advantages, but I gave up on it when my tests failed in IDE but passed in Terminal. At the moment, though I do go through a set of manual setup steps, it has become routine. So I am good. Thanks for the tip though!

**Comment by itzsaga** [comment]
I as well have to say this lab is somewhat confusing. More because it deviates so greatly from everything before it. I think having the boilerplate Bootstrap, with index.html template, and exceptional realty folders (images, videos, fonts) would make this easier to follow. However, I also understand that we're learning to code and in that process we need to learn to solve problems.

**Comment by mohibhashimi786** [comment]
Hello all - 
The only way I got the last lab to submit correctly was to copy all the files from the "exceptional realty bootstrap" lab into the "layout-grids-code-along" lab.  And then again from the exceptional realty bootstrap to the "bootstrap navbar codealong".  However, as others have mentioned, files don't copy and i repeatedly got error messages, especially trying to import or copy the images or videos.  I did notice if you find the images and videos location on your desktop and import them from there, then it would work.  

I love this program but sometimes LEARN makes me want to run into a wall.  Simple copy and paste into a program should not initiate so many errors and freezes.

**Comment by Rygel-XVI** [comment]
I strongly suggest adding in the files that were completed in the previous codealongs. I am working on two different machines in a local environment and the old codealongs aren't on this machine and so far in this program we haven't practiced pulling any files from github or pushing and pulling from different repositories or reassociating branches with different projects. I think I can figure it out but it's definitely going to be a massive inconvenience as I have to figure out how to do something I haven't done before.

**Comment by DeedaG** [comment]
I am relieved to know that I am not the only person who has experienced these same issues for this lab.  :)

**Comment by jenmyers** [comment]
Hello! We have added some instructions to clarify how to access files and carry over progress. Also, a new version of this material will also be available soon to resolve the issue entirely.

-- Flatiron Curriculum Team
